CREATE TABLE Content (
	id VARCHAR(512) NOT NULL PRIMARY KEY,
	ip VARCHAR(1024) NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	data TEXT
);


DROP TABLE Access;
CREATE TABLE Access (
	id INT AUTO_INCREMENT PRIMARY KEY,
	ip VARCHAR(1024) NOT NULL,
	req_id VARCHAR(512),
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

